# Generated by Django 4.2.7 on 2023-11-05 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_character'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('background', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(default='', max_length=50)),
                ('town', models.CharField(default='', max_length=50, null=True)),
                ('town_detail', models.TextField(default='', null=True)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.character')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gpt',
            fields=[
                ('gpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'system'), ('assistant', 'assi'), ('user', 'user')], max_length=10)),
                ('query', models.TextField(default='', null=True)),
                ('script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.script')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('final', '최종'), ('detail', '세부')], max_length=10)),
                ('content', models.TextField(default='')),
                ('finished', models.BooleanField(default=False)),
                ('script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.script')),
            ],
        ),
    ]
