# Generated by Django 4.2.7 on 2023-11-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_character_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('script_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('background', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(default='', max_length=50)),
                ('town', models.CharField(default='', max_length=50, null=True)),
                ('town_detail', models.TextField(default='', null=True)),
                ('character', models.OneToOneField(db_column='character_id', on_delete=django.db.models.deletion.CASCADE, related_name='script', to='account.character')),
            ],
        ),
    ]
