# Generated by Django 4.2.7 on 2023-11-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_final', models.BooleanField(default=False)),
                ('content', models.TextField(default='')),
                ('finished', models.BooleanField(default=False)),
                ('script', models.ForeignKey(db_column='script_id', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='scenario.script')),
            ],
        ),
    ]
