# Generated by Django 4.2.7 on 2023-11-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='is_final',
            new_name='final',
        ),
    ]
