# Generated by Django 4.2.7 on 2023-11-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0003_rename_is_final_goal_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gpt',
            fields=[
                ('gpt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'system'), ('assistant', 'assistant'), ('user', 'user')], max_length=10)),
                ('query', models.TextField(default='', null=True)),
                ('script', models.ForeignKey(db_column='script_id', on_delete=django.db.models.deletion.CASCADE, related_name='gpts', to='scenario.script')),
            ],
        ),
    ]
